### ISSUE TITLE
getTemplates gives nullpointerException

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#138]

**Comment by LindaVels** [comment]
getTemplates API call geeft een Nullpoiter exception in de viewer. De stack trace van de geoideWebService is:


09:53:14.850 [service-akka.actor.default-dispatcher-3] ERROR akka.remote.EndpointWriter - Transient association error (association remains live)
java.io.NotSerializableException: No configured serialization-bindings for class [com.fasterxml.jackson.databind.node.ObjectNode]
        at akka.serialization.Serialization.serializerFor(Serialization.scala:145) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.serialization.Serialization.findSerializerFor(Serialization.scala:123) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:34) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:845) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:845) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:844) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointWriter.writeSend(Endpoint.scala:747) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:722) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:415) ~[geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [geoide-web-service-0.5.1-SNAPSHOT.jar:na]

**Comment by erikorbons** [comment]
Hier wordt kennelijk ergens een JSON ObjectNode geserialiseerd in één van de objecten die wordt gereturned uit deze aanroep. Dat kan niet.

Je kunt deze in het betreffende object vervangen door ExternalizableJsonNode, die is wel serialiseerbaar (hiervan zijn verschillende voorbeelden te vinden).
