### ISSUE TITLE
report gives error

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#141]

**Comment by LindaVels** [comment]
printing a map gives following error message in the client:

**Comment by erikorbons** [comment]
Hier ontbreekt denk ik een mapping voor de DocumentCache in de configuratie van de Play applicatie. Er wordt hier gewerkt met een Guice module, die kun je met behulp van de Play documentatie denk ik wel vinden (Play 2.4).

**Comment by erikorbons** [comment]
DocumentCache added to application context, new exceptions:

```
java.lang.NullPointerException: null
        at controllers.printservice.Report$2.apply(Report.java:74) ~[geoide-print-service_2.11.jar:0.1.8-SNAPSHOT]
        at controllers.printservice.Report$2.apply(Report.java:68) ~[geoide-print-service_2.11.jar:0.1.8-SNAPSHOT]
        at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:103) ~[play_2.11-2.4.0.jar:2.4.0]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
        at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [play_2.11-2.4.0.jar:2.4.0]
```
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-
2.4.0.jar:2.4.0]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.
4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273
) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269
) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
Caused by: java.lang.NullPointerException: null
        at controllers.printservice.Report$2.apply(Report.java:74) ~[geoide-print-service_2.11.jar:0.1.8-SNAPSHOT]
        at controllers.printservice.Report$2.apply(Report.java:68) ~[geoide-print-service_2.11.jar:0.1.8-SNAPSHOT]
        at play.core.j.FPromiseHelper$$anonfun$map$1.apply(FPromiseHelper.scala:103) ~[play_2.11-2.4.0.jar:2.4.0]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
        at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [play_2.11-2.4.0.jar:2.4.0]
```

**Comment by erikorbons** [comment]
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RemoteServiceException: No mapping for method nl.
idgis.geoide.commons.domain.api.DocumentCache#fetch(java.net.URI)]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-
2.4.0.jar:2.4.0]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.
4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstream
Handler.scala:158) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstream
Handler.scala:155) [play-netty-server_2.11-2.4.0.jar:2.4.0]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.6.jar:na]
Caused by: nl.idgis.geoide.commons.remote.RemoteServiceException: No mapping for method nl.idgis.geoide.commons.domain.a
pi.DocumentCache#fetch(java.net.URI)
        at nl.idgis.geoide.commons.remote.RemoteServiceFactory.lambda$createRemoteMethodServer$3(RemoteServiceFactory.ja
va:81) ~[geoide-remote-0.1.8-SNAPSHOT.jar:na]
        at nl.idgis.geoide.commons.remote.RemoteServiceFactory$$Lambda$7/1295803795.invokeMethod(Unknown Source) ~[na:na
]
        at nl.idgis.geoide.commons.remote.transport.RemoteMethodServerActor.onReceive(RemoteMethodServerActor.java:51) ~
[geoide-remote-0.1.8-SNAPSHOT.jar:na]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[akka-actor_2.11-2.3.11.jar:n
a]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[akka-actor_2.11-2.3.11.jar:na]
```

**Comment by erikorbons** [comment]
Made resulting documents from a print serializable over Akka, remaining issue: document body for a typical print result can easily exceed the maximum message size. Large documents should be split when returning a publisher from the document cache.
