### ISSUE TITLE
NPE if print template path doesn't exist

### ISSUE THREAD

**Issue by erikorbons** [IDgis/geoide-commons#144]
```
Caused by: java.lang.NullPointerException: null
        at nl.idgis.geoide.commons.report.template.HtmlTemplateDocumentProvider.getTemplates(HtmlTemplateDocumentProvide
r.java:112) ~[na:na]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636) ~[na:1.8.0_31]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:658) ~[na:1.8.0_31]
        at nl.idgis.geoide.commons.remote.RemoteServiceFactory.lambda$0(RemoteServiceFactory.java:86) ~[geoide-remote-0.
1.8-SNAPSHOT.jar:na]
        at nl.idgis.geoide.commons.remote.RemoteServiceFactory$$Lambda$7/1410431463.invokeMethod(Unknown Source) ~[na:na
]
        at nl.idgis.geoide.commons.remote.transport.RemoteMethodServerActor.onReceive(RemoteMethodServerActor.java:39) ~
[geoide-remote-0.1.8-SNAPSHOT.jar:na]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[akka-actor_2.11-2.3.11.jar:n
a]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.11-2.3.11.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.11.jar:na]
```

**Comment by erikorbons** [comment]
Modified to return an empty set of templates instead.
