### ISSUE TITLE
Promise already completed after print

### ISSUE THREAD

**Issue by erikorbons** [IDgis/geoide-commons#26]
After completing a print task, a sequence of "Promise already completed" exceptions is thrown, followed by a timeout on several actors.

Possibly streams are not closed or the actor is not stopped after the stream closes when consuming a stream.

**Comment by erikorbons** [comment]
Stacktrace:

```
java.lang.IllegalStateException: Promise already completed.
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.Promise$class.failure(Promise.scala:107)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
        at nl.idgis.geoide.util.streams.AkkaStreamProcessor$1.onError(AkkaStreamProcessor.java:75)
        at nl.idgis.geoide.util.streams.AkkaStreamProcessor$InputStreamPublishActor.onReceive(AkkaStreamProcessor.java:4
53)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
