### ISSUE TITLE
50  bug while printing tile maps to svg in the printservice

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#50]

**Comment by LindaVels** [comment]
Search on internet suggests that there is a memory problem.
tried to increase memory by:
set "JAVA_OPTS=-Xmx:2048m"
before starting running the application.
Got an error:
Invalid maximum heap size: -Xmx:2048m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by erikorbons** [comment]
@LindaVels: ``-Xmx2048m``

**Comment by LindaVels** [comment]
Printing each tile to a seperate svg file solves part of the problem. Sometimes one or more tiles are not printed and te same error is thrown:

The URI "http://geodata.nationaalgeoregister.nl/tms/1.0.0/brtachtergrondkaart/1.0.0/9/290/205.png"
on element <image> can't be opened because:
JDK URL is corrupt or unsupported variant
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:227)
        at org.apache.batik.transcoder.print.PrintTranscoder.transcode(PrintTranscoder.java:159)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.transcoder.print.PrintTranscoder.print(PrintTranscoder.java:307)
        at nl.idgis.geoide.commons.print.svg.SVGReplacedElement.paint(SVGReplacedElement.java:92)
        at org.xhtmlrenderer.pdf.ITextOutputDevice.paintReplacedElement(ITextOutputDevice.java:202)
        at org.xhtmlrenderer.layout.Layer.paintReplacedElement(Layer.java:540)
        at org.xhtmlrenderer.layout.Layer.paintReplacedElements(Layer.java:497)
        at org.xhtmlrenderer.layout.Layer.paint(Layer.java:333)
        at org.xhtmlrenderer.layout.Layer.paintLayers(Layer.java:165)
        at org.xhtmlrenderer.layout.Layer.paint(Layer.java:340)
        at org.xhtmlrenderer.pdf.ITextRenderer.paintPage(ITextRenderer.java:401)
        at org.xhtmlrenderer.pdf.ITextRenderer.writePDF(ITextRenderer.java:349)
        at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:306)
        at org.xhtmlrenderer.pdf.ITextRenderer.createPDF(ITextRenderer.java:243)
        at nl.idgis.geoide.commons.print.service.HtmlPrintService$1.run(HtmlPrintService.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
ERROR: null

It looks like the error is thrown on a timeout?

**Comment by LindaVels** [comment]
Aparantly this error is only triggered when the tiling service is slow resulting in a kind of time-out. When the error is raised one or more tiles will be missing on the print. This problem is not indicated as being urgent. Will not be solved now.
